### ISSUE TITLE
No Update Coming ?

### ISSUE THREAD

**Issue by skaox** [UnnoTed/wireguird#1]
Hello,

problem in compilation because go-appindicator is now v1.0.1

go.sum:
github.com/dawidd6/go-appindicator v1.0.1 h1:Jds+9T6dd2SpZ4krJ6SaGdwlKzGTjuU9AypHWhTOXCY=
github.com/dawidd6/go-appindicator v1.0.1/go.mod h1:hOqBUkquzU53HlXUFjFXHAkzdyD45TmTZCQb3FqtEWg=

I would really like to use it instead Qomui where there is no more update since september 2019.

No update coming on wireguird ?

Thank you in advance

**Comment by skaox** [comment]
**13 days later still no answer !**

I didn't found out how to launch it with pkexec or gksudo and having the icons ?

**Sometimes it crash :**

fatal error: unexpected signal during runtime execution
*** BUG ***
In pixman_region_append_non_o: The expression r->x1 < r->x2 was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region_append_non_o: The expression r->x1 < r->x2 was false
Set a breakpoint on '_pixman_log_error' to debug

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f733f53bf26]

runtime stack:
runtime.throw(0xc3fe02, 0x2a)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0xa7a890, 0xc000345d10, 0xc00009f4a0)
	/usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc000345ce0 sp=0xc000345ca8 pc=0x4736fb
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x28db0f0, 0x1, 0x28d7a30, 0x0)
	_cgo_gotypes.go:1236 +0x4d fp=0xc000345d10 sp=0xc000345ce0 pc=0x5fb1ad
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc00009f4a0, 0xc00009a190, 0x1, 0x1, 0x28d7a30, 0x28ddf60)
	/home/skaox/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/glib/application.go:202 +0xa6 fp=0xc000345d50 sp=0xc000345d10 pc=0x60ab56
github.com/gotk3/gotk3/glib.(*Application).Run(0xc00009f4a0, 0xc00009a190, 0x1, 0x1, 0x0)
	/home/skaox/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/glib/application.go:202 +0x181 fp=0xc000345df0 sp=0xc000345d50 pc=0x600e91
main.main()
	/home/skaox/Downloads/WIREGUIRD/wireguird-0.1/main.go:39 +0x3ee fp=0xc000345f60 sp=0xc000345df0 pc=0xa76f1e
runtime.main()
	/usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc000345fe0 sp=0xc000345f60 pc=0x49fb3e
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000345fe8 sp=0xc000345fe0 pc=0x4ca8e1

goroutine 19 [select, locked to thread]:
github.com/mdlayher/netlink.newLockedNetNSGoroutine.func1(0xc0000c0101, 0xc0000bab80, 0xc4d338, 0xc0000c0120, 0xc0000a6d80, 0xc00009b3f0)
	/home/skaox/go/pkg/mod/github.com/mdlayher/netlink@v1.1.0/conn_linux.go:738 +0x220
created by github.com/mdlayher/netlink.newLockedNetNSGoroutine
	/home/skaox/go/pkg/mod/github.com/mdlayher/netlink@v1.1.0/conn_linux.go:669 +0x227

goroutine 35 [syscall]:
github.com/gotk3/gotk3/gtk._Cfunc_gtk_label_set_text(0x2c3bee0, 0x2d9b3e0)
	_cgo_gotypes.go:14120 +0x41 fp=0xc000277c18 sp=0xc000277be8 pc=0x665a21
github.com/gotk3/gotk3/gtk.(*Label).SetText.func2(0xc0002da2d0, 0x2d9b3e0)
	/home/skaox/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/label.go:66 +0x6e fp=0xc000277c58 sp=0xc000277c18 pc=0x71970e
github.com/gotk3/gotk3/gtk.(*Label).SetText(0xc0002da2d0, 0xc000477410, 0xc)
	/home/skaox/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/label.go:66 +0x88 fp=0xc000277cc0 sp=0xc000277c58 pc=0x6cbec8
github.com/UnnoTed/wireguird/gui.(*Tunnels).Create.func4(0xc0002ea310, 0xc0002da038)
	/home/skaox/Downloads/WIREGUIRD/wireguird-0.1/gui/tunnels.go:346 +0x3f0 fp=0xc000277fd0 sp=0xc000277cc0 pc=0xa31080
created by github.com/UnnoTed/wireguird/gui.(*Tunnels).Create
	/home/skaox/Downloads/WIREGUIRD/wireguird-0.1/gui/tunnels.go:316 +0xbc6
[signal SIGSEGV: segmentation violation code=0x1 addr=0x42d273c0 pc=0x7f733fd76ed7]

runtime stack:
runtime.throw(0xc3fe02, 0x2a)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

**Ubuntu Mate 20.04
go version go1.13.8 linux/amd64**

**Comment by UnnoTed** [comment]
I'm currently having health issues so don't expect updates any time soon after now...
Anyways, try the deb package from https://github.com/UnnoTed/wireguird/releases/tag/v0.1.0

if you prefer to build it, try `mkdir build && package.sh`

**Comment by skaox** [comment]
Just perfect a big THANK YOU.

Noted, no more updates any time soon.

I wish you a good recovery. Take care
