### ISSUE TITLE
"Exit status 1" error on Ubuntu

### ISSUE THREAD

**Issue by nurekella** [UnnoTed/wireguird#11]
Hi.
Please help what I'm doing wrong.
When I press activate button, there's "Exit status 1" error appears.
![wireguird](https://user-images.githubusercontent.com/52822736/204207734-3a2e57ee-cfb6-46d6-95f8-0169f3b0c5e2.png)

**Comment by redzjovi** [comment]
The maximum length is defined by IFNAMSIZ (16), which means at most 15 characters plus terminating null character.
Try to rename to config filename length.

Or up via Terminal.

`wg-quick up <configfile>.`

**Comment by skaox** [comment]
Same problem and confirm solved by reducing the name 15 characters ;-)

**Comment by nurekella** [comment]
Thanks for your help brother

**Comment by UnnoTed** [comment]
> The maximum length is defined by IFNAMSIZ (16), which means at most 15 characters plus terminating null character. Try to rename to config filename length.
> 
> Or up via Terminal.
> 
> `wg-quick up <configfile>.`

Added a check for that in the new version.

Now WireguArd's errors will appear both in a dialog and in the log tab.
