### ISSUE TITLE
wireguird: building go binary... Failed

### ISSUE THREAD

**Issue by linuxzilla** [UnnoTed/wireguird#2]
Hi man!
Sorry my english a little bit broken. I haven't talk for ages on this language.
So I tried to compile your application but it didn't finished and it throw me this error massege.

`../../go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/accel.go:261:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../../go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/accel.go:270:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
`
I'm currently using Pop OS 20.10 (basically a ubuntu 20.10)

**Comment by skaox** [comment]
Hi,

the author/creator is having health issues so don't expect updates or help any time soon ; I hope he's better now.

I tried to compile it and had no errors with my Ubuntu 20.04 but didn't tried 20.10.

I don't use the compiled executable of 24.7 MB but use the deb package who gives in /opt/wireguird/ one of 17.1 MB.

Can't you install the deb package ? [wireguird_amd64.deb](https://github.com/UnnoTed/wireguird/releases/download/v0.1.0/wireguird_amd64.deb)

**Comment by linuxzilla** [comment]
Hello!
Sad to hear :/  I also hope he will get better soon.
Sorry I haven't noticed the packaged version of the program. The package manager installed it without any problems. And It working fine on Pop OS 21.04 (I'm upgrded to the newest vession) . So this is a really cool and simple application :D . Although the add tunnel and edit tunnel buttons aren't working on my system, nevertheless I love it :D

Thanks  for the help!
