### ISSUE TITLE
How to run without root password?

### ISSUE THREAD

**Issue by Crazy-kun** [UnnoTed/wireguird#28]
How can i run wireguird without entering a root password every time?

**Comment by iptvcld** [comment]
looking for the same answer. thanks

**Comment by iptvcld** [comment]
got it..
sudo visudo
Add the folllwing line in at the bottom (replace username with your username)
USERNAME ALL=(root) NOPASSWD: /usr/local/bin/wireguird
save the file

Add the app in Applcation Startup and edit the line with the path to the app by adding sudo in front (sudo /usr/local/bin/wireguird)

**Comment by SAOPP** [comment]
Btw, I tried a similar option, but it didn't work for me on Ubuntu 22.
