### ISSUE TITLE
Does not work with Ubuntu 22.04 - "Cannot install libappindicator3-dev"

### ISSUE THREAD

**Issue by yllekz** [UnnoTed/wireguird#7]
Hello, it seems this app doesn't work with Linux Mint 21 which uses Ubuntu 22.04.

Trying to install the .deb results in ``Error: Cannot install 'libappindicator3-dev'``

**Comment by Luca8991** [comment]
Same here, I'm getting the error:
```
wireguird depends on libappindicator3-dev (>= 1.0.0); however:
  Package libappindicator3-dev is not installed.
```
and when trying to install `libappindicator3-dev`:
```
The following packages have unmet dependencies:
 libayatana-appindicator3-1 : Conflicts: libappindicator3-1
```

System info:
- `lsb_release -a`
    ```
    Distributor ID:	Ubuntu
    Description:	Ubuntu 22.04.1 LTS
    Release:	22.04
    Codename:	jammy
    ```

- `uname -a`
    ```
    Linux mypc 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    ```

**Comment by yllekz** [comment]
So the weirdest thing happened today...now I'm able to install it just fine and I'm not sure what I did differently to suddenly make it work. 

This was all I ran:

```
wget -O ~/Downloads/wireguird.deb https://github.com/UnnoTed/wireguird/releases/download/v0.2.0/wireguird_amd64.deb
sudo dpkg -i ~/Downloads/wireguird.deb

```

Strange that it didn't work the other day but decided to work today...

**Comment by yllekz** [comment]
Another update, and this one is a doozy:

So the above workaround does work, but what I didn't realize was that it removes the entire Blueman Bluetooth stack that Linux Mint 21 now uses.

Attempting to reinstall blueman warns that libappindicator3-1, libappindicator3-dev, and wireguird will all be removed:

```
The following additional packages will be installed:
  gir1.2-ayatanaappindicator3-0.1 libayatana-appindicator3-1
The following packages will be REMOVED:
  libappindicator3-1 libappindicator3-dev wireguird
```

so right now you have to choose either between Wireguird or having Bluetooth...

**Comment by mkono87** [comment]
Same issue here on mint 21 also. Im glad I didnt try the workaround.

**Comment by yllekz** [comment]
@tekkman yes but check if your bluetooth stack is stil present. As mentioned, the issue is you lose bluetooth support if you install via that path.

**Comment by skaox** [comment]
Ubuntu Mate 22.04 with the workaround I lose Bluetooth and Network(-manager).

**Comment by cosme12** [comment]
> Ubuntu Mate 22.04 with the workaround I lose Bluetooth (blueman) and Network (network-manager).
> 
> ```
> apt install libappindicator3-1
> 
> The following packages will be REMOVED :
>   ayatana-indicator-application blueman gir1.2-ayatanaappindicator3-0.1 libayatana-appindicator3-1 mate-optimus network-manager-gnome redshift-gtk transmission-gtk ubuntu-mate-core
>   ubuntu-mate-desktop ubuntu-release-upgrader-gtk update-manager update-notifier
> ```
> 
> For Ubuntu 22.04 and newer **libayatana-appindicator3-dev should be used instead of libappindicator3-dev**
> 
> (-: I changed the dependencies required and it work like a charm ;-)
> 
> [wireguird_amd64_libayatana-appindicator3-dev.zip](https://github.com/UnnoTed/wireguird/files/10330190/wireguird_amd64_libayatana-appindicator3-dev.zip)
> 
> Couldn't upload the deb package so after download change the extension .zip to .deb

Working great! Thanks

**Comment by josecarlos19** [comment]
> Ubuntu Mate 22.04 with the workaround I lose Bluetooth (blueman) and Network (network-manager).
> 
> ```
> apt install libappindicator3-1
> 
> The following packages will be REMOVED :
>   ayatana-indicator-application blueman gir1.2-ayatanaappindicator3-0.1 libayatana-appindicator3-1 mate-optimus network-manager-gnome redshift-gtk transmission-gtk ubuntu-mate-core
>   ubuntu-mate-desktop ubuntu-release-upgrader-gtk update-manager update-notifier
> ```
> 
> For Ubuntu 22.04 and newer **libayatana-appindicator3-dev should be used instead of libappindicator3-dev**
> 
> (-: I changed the dependencies required and it work like a charm ;-)
> 
> [wireguird_amd64_libayatana-appindicator3-dev.zip](https://github.com/UnnoTed/wireguird/files/10330190/wireguird_amd64_libayatana-appindicator3-dev.zip)
> 
> Couldn't upload the deb package so after download change the extension .zip to .deb

Works on Linux Mint 21.1!

**Comment by yllekz** [comment]
Workaround works for me too, thanks!

**Comment by TheNomad11** [comment]
> Ubuntu Mate 22.04 with the workaround I lose Bluetooth (blueman) and Network (network-manager).
> 
> ```
> apt install libappindicator3-1
> 
> The following packages will be REMOVED :
>   ayatana-indicator-application blueman gir1.2-ayatanaappindicator3-0.1 libayatana-appindicator3-1 mate-optimus network-manager-gnome redshift-gtk transmission-gtk ubuntu-mate-core
>   ubuntu-mate-desktop ubuntu-release-upgrader-gtk update-manager update-notifier
> ```
> 
> For Ubuntu 22.04 and newer **libayatana-appindicator3-dev should be used instead of libappindicator3-dev**
> 
> (-: I changed the dependencies required and it work like a charm ;-)
> 
> [wireguird_amd64_libayatana-appindicator3-dev.zip](https://github.com/UnnoTed/wireguird/files/10330190/wireguird_amd64_libayatana-appindicator3-dev.zip)
> 
> Couldn't upload the deb package so after download change the extension .zip to .deb

Thanks so much, works now on Linux Mint 21.1

**Comment by UnnoTed** [comment]
Fixed in v1, it uses `libayatana-appindicator3` now.
