### ISSUE TITLE
Multiple Tunnels Open at Once

### ISSUE THREAD

**Issue by T313C0mun1s7** [UnnoTed/wireguird#8]
I have three tunnels. Two are to the local LAN of remote offices, and one is to an EC2 instance on AWS. There are no overlaps in the remote LAN subnets, or the tunnel subnets. The AWS instance has a Allow IPs of 0.0.0.0/0 and becomes my internet gateway. The remote offices have Allow IPs set for the subnet scope of the remote LAN and only become a route for that remote LAN. All tunnels work as they should independently. However, if I have a tunnel active and I activate a different tunnel, the active one deactivates. In web form terms, they act like radio select bubbles, and not check boxes. Is there any way to get WireGUIrd to to let me have all three active at the same time?

Thank you.

**Comment by pkoevesdi** [comment]
I can confirm: normally I can activate both of my tunnels, with wireguird I can't. I can even activate one in Wireguird and the other with wg-quick.
